# The configuration file is a yaml file that follows yaml format
#
# The directory to your dataset
# The data must be organized as /path/to/dataset/your_video_name/src/%010d.png, start from id=0
# We use png to avoid error caused by jpeg compression
data_dir: D:\chicago\videos
#
# Set the default value of parameters here
# All the parameters here will be forwarded to each instance
# You can add any variables here as long as you obey the basic yaml format.
# So please use this part nicely to avoid hard-coding.
# You could specify multiple values for each parameter through yaml list. The code will automatically sweep all parameters for you
default:
  # overwrite existing results or not
  overwrite: False
  # the video name you want to run
  video_name: trafficcam_3
  # several configurations for object detection
  max_object_size: 0.3
  low_threshold: 0.3
  high_threshold: 0.8
  enforce_iframes: True
  verbosity: info
  simulate: False
  intersection_threshold: 0.3
  low_results_path: None
  high_results_path: None
  high_resolution: -1
  high_qp: -1
  estimate_banwidth: False
  low_images_path: None
  tracker_length: 4
  # the size of a video chunk
  batch_size: 15
  min_object_size: 0
  boundary: 0.2
  tracking_threshold: 0.3
  suppression_threshold: 0.5
  rpn_enlarge_ratio: 0
   # The score to prune out those low-objectness-score regions. Just to control the bandwidth
  prune_score: 0.5
  # Two regions will be treated as the same region if the intersection-over-union (IoU) is larger than this threshold
  objfilter_iou: 0.3
  # control the size of the object for proposed region
  size_obj: 0.01
  # configuration for semantic segmentation
  class_id: 7
  num_sqrt: 3
  kernel_size: 64
  high_obj_size_semantic_segmentation: 0.007
  # Turn on debug_mode to show what DDS sends in second iteration.
  debug_mode: False
  # The path to the ground truth. Will be automatically set in entrance.py
  ground_truth: False
  mode: emulation
  hname: False
  application: semantic_segmentation
  req_regions_fname: False
#
# Specify each instance here
# You could overwrite the default configuration for each instance
# The configuration will be directly forwarded to the server
# You could specify multiple values for each parameter through yaml list
# We will automatically spawn multiple instances for you
# E.g., if you specify qp = [1,2], resolution = [0.6,0.8]
# You will get four instances with (qp,resolution)=(1,0.6),(1,0.8),(2,0.6),(2,0.8)
instances:
- method: gt
  # quantization parameter, higher qp means worse quality.
  low_qp: 24
  # resolution is a number in (0, 1]. We will scale the width and the hight according to this factor.
  low_resolution: 1.0
- method: mpeg
  low_qp:
  - 36
  - 26
  low_resolution: 1.0
- batch_size: 15
  # the configuration for the Stream A (low) and Stream B (high)
  high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: dds
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0

# the configuration for the streamB pack: region-region
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: region
  context_val:
    - 0.0
    - 0.3
    - 0.5
    - 1.0
  blank_padding_type: region
  blank_val:
    - 0.0
    - 0.3
    - 0.5
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: region-inverse
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: region
  context_val:
    - 0.0
    - 0.3
    - 0.5
    - 1.0
  blank_padding_type: inverse
  blank_val:
    - 0.0005
    - 0.0001
    - 0.001
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: region-whole
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: region
  context_val:
    - 0.0
    - 0.3
    - 0.5
    - 1.0
  blank_padding_type: whole
  blank_val:
    - 0.01
    - 0.03
    - 0.05
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: inverse-region
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: inverse
  context_val:
    - 0.0005
    - 0.0003
    - 0.0001
    - 0.001
  blank_padding_type: region
  blank_val:
    - 0.0
    - 0.3
    - 0.5
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: inverse-inverse
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: inverse
  context_val:
    - 0.0005
    - 0.0003
    - 0.0001
    - 0.001
  blank_padding_type: inverse
  blank_val:
    - 0.0005
    - 0.0001
    - 0.001
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: inverse-whole
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: inverse
  context_val:
    - 0.0005
    - 0.0003
    - 0.0001
    - 0.001
  blank_padding_type: whole
  blank_val:
    - 0.01
    - 0.03
    - 0.05
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou:
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

- # the configuration for the streamB pack: whole-region
  high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: whole
  context_val:
    - 0.01
    - 0.03
    - 0.05
    - 0.07
  blank_padding_type: region
  blank_val:
    - 0.0
    - 0.3
    - 0.5
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: whole-inverse
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: whole
  context_val:
    - 0.01
    - 0.03
    - 0.05
    - 0.07
  blank_padding_type: inverse
  blank_val:
    - 0.0005
    - 0.0001
    - 0.001
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: whole-whole
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: whole
  context_val:
    - 0.01
    - 0.03
    - 0.05
    - 0.07
  blank_padding_type: whole
  blank_val:
    - 0.01
    - 0.03
    - 0.05
  area_upper_bound:
    - 0.0005
    - 0.001
  resize_type:  
    - fixed_ratio
  fixed_area: 
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou:
    - 1.0
    - 0.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: pixel-region     
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: pixel
  context_val:
    - 0.0027
    - 0.01
    - 0.038
    - 0.054
  blank_padding_type: region
  blank_val:
    - 0.0
    - 0.3
    - 0.5
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 0.0
    - 1.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: pixel-inverse
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: pixel
  context_val:
    - 0.0027
    - 0.01
    - 0.038
    - 0.054
  blank_padding_type: inverse
  blank_val:
    - 0.0005
    - 0.0001
    - 0.001
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou: 
    - 0.0
    - 1.0
  compare_gt: False
  cleanup: True
  track_region: False

# the configuration for the streamB pack: pixel-whole  
- high_qp: 26
  high_resolution: 1.0
  low_qp: 36
  low_resolution: 1.0
  method: streamBpack
  # Deprecated parameter
  rpn_enlarge_ratio: 0.0
  # context padding
  context_padding_type: pixel
  context_val:
    - 0.0027
    - 0.01
    - 0.038
    - 0.054
  blank_padding_type: whole
  blank_val:
    - 0.01
    - 0.03
    - 0.05
  area_upper_bound: 
    - 0.0005
    - 0.001
  resize_type: 
    - fixed_ratio
  fixed_area:
    - 0.001
    - 0.002
  fixed_ratio:
    - 1
    - 2
  intersect_iou: 0.2
  merge_iou:
    - 0.0
    - 1.0
  compare_gt: False
  cleanup: True
  track_region: False

